### ISSUE TITLE
Programming Exercises

### ISSUE THREAD

**Issue by githwxi** [jats-ug/ATS_Foundations#1]
First, I want to give you a round of applause for starting this!

My first suggestion is that you prepare some (simple) programming exercises for the reader to try.

**Comment by master-q** [comment]
Thank's. I write this book on the OCaml book "プログラミングの基礎 (Programming Foundations)".

http://www.amazon.co.jp/dp/4781911609

I'll try to sort the chapters for your suggestion.

**Comment by master-q** [comment]
Add some exercises into "Basic data types" chapter.

http://jats-ug.metasepi.org/doc/ATS2/ATS_Foundations/basic_datatype.html

**Comment by master-q** [comment]
And so, I decide to write this book in English!

**Comment by githwxi** [comment]
It is great. Then I will be able to help from time to time :)

Also, I can recommend it to the students who take classes I teach.

Cheers!
